- id: 'vriendje'
  name: Vriend
  categories:
    - 8293 # taal - nederlandse boeken
    - 19
    - 8292 # Engelse boeken
    - 4294754280
    - 3132 # muziek totaal
    - 6080 # Muziek POP
    - 6142 # Film + tv Actie en Avontuur
    - 6196 # Film + tv Humor
    - 11551 # Games XBOX One
    - 11642 # Games Playstaytion 4
    - 5201 # Games PC
    - 10500 # Speelgoed Electronisch speelgoed
    - 10579
    - 10596
    - 12432 # Mooi en gezond Herengeuren
    - 4098
    - 8427
    - 8431
    - 8429
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10824
    - 10836
    - 10728
    - 10727
    - 10730
    - 10732

- id: 'vriendinnetje'
  name: Vriendin
  categories:
    - 8293 # taal - nederlandse boeken
    - 19
    - 8292 # Engelse boeken
    - 4284431352
    - 3132 # muziek totaal
    - 6080 # Muziek POP
    - 6196 # Film + tv Humor
    - 6230 # Film + tv drama en romantiek
    - 6251 # Film + tv Thrillers & Crime
    - 10508 # handwerken en mode
    - 10511 # Koken en bakken
    - 12383
    - 12429 # Mooi en gezond Damesgeuren
    - 12687 # Mooi en gezond Persoonlijke verzorging geschenksets
    - 12441 # Mooi en gezond Geurengeschenksets
    - 4098
    - 8427
    - 8431
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10829
    - 10832
    - 14768 # Sport - Pilates en Yoga

- id: 'vader'
  name: Voor je vader
  categories:
    - 8293 # taal - nederlandse boeken
    - 19
    - 8292 # Engelse boeken
    - 4294754280
    - 6080 # Muziek POP
    - 6142 # Film + tv Actie en Avontuur
    - 6158
    - 6196 # Film + tv Humor
    - 10579
    - 10596
    - 12432 # Mooi en gezond Herengeuren
    - 11773
    - 11785
    - 11826
    - 8429
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10824
    - 10836
    - 10771
    - 10798
    - 10799
    - 10802
    - 10800
    - 10728
    - 10727
    - 10730
    - 10732

- id: 'moeder'
  name: Voor je moeder
  categories:
    - 8293 # taal - nederlandse boeken
    - 19
    - 8292 # Engelse boeken
    - 6080 # Muziek POP
    - 6177 # Film + tv Filmhuis en internationaal
    - 6196 # Film + tv Humor
    - 6230 # Film + tv drama en romantiek
    - 6251 # Film + tv Thrillers & Crime
    - 10508 # handwerken en mode
    - 10511 # Koken en bakken
    - 10506 # Boetseren en vormgeven
    - 10564 # legpuzzels
    - 12383
    - 12429 # Mooi en gezond Damesgeuren
    - 12687 # Mooi en gezond Persoonlijke verzorging geschenksets
    - 12441 # Mooi en gezond Geurengeschenksets
    - 11773
    - 11785
    - 11826
    - 11922
    - 11927
    - 11888
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10829
    - 10832
    - 10771
    - 10798
    - 10799
    - 10802
    - 10800
    - 14768 # Sport - Pilates en Yoga

- id: 'broertje'
  name: Voor je broertje
  categories:
    - 8293 # taal - nederlandse boeken
    - 19
    - 8292 # Engelse boeken
    - 4294754280
    - 3132 # muziek totaal
    - 6142 # Film + tv Actie en Avontuur
    - 6196 # Film + tv Humor
    - 11551 # Games XBOX One
    - 11642 # Games Playstaytion 4
    - 5201 # Games PC
    - 10500 # Speelgoed Electronisch speelgoed
    - 10579
    - 10596
    - 12432 # Mooi en gezond Herengeuren
    - 4098
    - 8427
    - 8431
    - 8429
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10824
    - 10836
    - 10728
    - 10727
    - 10730
    - 10732

- id: 'zusje'
  name: Voor je zusje
  categories:
    - 8293 # taal - nederlandse boeken
    - 19
    - 8292 # Engelse boeken
    - 4284431352
    - 3132 # muziek totaal
    - 6080 # Muziek POP
    - 6196 # Film + tv Humor
    - 6230 # Film + tv drama en romantiek
    - 10508 # handwerken en mode
    - 10511 # Koken en bakken
    - 10506 # Boetseren en vormgeven
    - 12383
    - 12429 # Mooi en gezond Damesgeuren
    - 12687 # Mooi en gezond Persoonlijke verzorging geschenksets
    - 12441 # Mooi en gezond Geurengeschenksets
    - 4098
    - 8427
    - 8431
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10829
    - 10832
    - 14768 # Sport - Pilates en Yoga

- id: 'baby'
  name: Voor een baby
  categories:
    - 10528
    - 10535
    - 10477
    - 11299
    - 11285
    - 7195

- id: 'oma'
  name: Voor je oma
  categories:
    - 8293 # taal - nederlandse boeken
    - 19
    - 6046
    - 10508 # handwerken en mode
    - 10511 # Koken en bakken
    - 10506 # Boetseren en vormgeven
    - 10564 # legpuzzels
    - 12383
    - 12429 # Mooi en gezond Damesgeuren
    - 12687 # Mooi en gezond Persoonlijke verzorging geschenksets
    - 12441 # Mooi en gezond Geurengeschenksets
    - 11773
    - 11785
    - 11826
    - 11922
    - 11927
    - 11888
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10829
    - 10832
    - 10771
    - 10798
    - 10799
    - 10802
    - 10800

- id: 'opa'
  name: Voor je opa
  categories:
    - 8293 # taal - nederlandse boeken
    - 19
    - 4294754280
    - 6046
    - 10564 # legpuzzels
    - 12432 # Mooi en gezond Herengeuren
    - 11773
    - 11785
    - 11826
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10824
    - 10836
    - 10771
    - 10798
    - 10799
    - 10802
    - 10800

# - id: 'huwelijk'
#   name: Een bruidspaar
#   categories:
#     - bla
