- id: 'vriendje'
  name: Vriend
  categories:
    - 1430 # Categorie - Nederlandse boeken
    - 19
    - 3131 # Categorie - Engelse Boeken
    - 105 # Boeken - Reisgidsen
    - 4294754280
    - 3132 # muziek totaal
    - 6080 # Muziek POP
    - 6142 # Film + tv Actie en Avontuur
    - 6196 # Film + tv Humor
    - 11551 # Games XBOX One
    - 11642 # Games Playstaytion 4
    - 5201 # Games PC
    - 10500 # Speelgoed Electronisch speelgoed
    - 10579
    - 10596
    - 12432 # Mooi en gezond Herengeuren
    - 4098
    - 8427
    - 8431
    - 8429
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10824
    - 10836
    - 10728
    - 10727
    - 10730
    - 10732

- id: 'vriendinnetje'
  name: Vriendin
  categories:
    - 1430 # Categorie - Nederlandse boeken
    - 19
    - 3131 # Categorie - Engelse Boeken
    - 105 # Boeken - Reisgidsen
    - 4284431352
    - 3132 # muziek totaal
    - 6080 # Muziek POP
    - 6196 # Film + tv Humor
    - 6230 # Film + tv drama en romantiek
    - 6251 # Film + tv Thrillers & Crime
    - 10508 # handwerken en mode
    - 10511 # Koken en bakken
    - 12383
    - 12429 # Mooi en gezond Damesgeuren
    - 12687 # Mooi en gezond Persoonlijke verzorging geschenksets
    - 12441 # Mooi en gezond Geurengeschenksets
    - 4098
    - 8427
    - 8431
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10829
    - 10832
    - 14768 # Sport - Pilates en Yoga

- id: 'vader'
  name: Voor je vader
  categories:
    - 1430 # Categorie - Nederlandse boeken
    - 19
    - 3131 # Categorie - Engelse Boeken
    - 105 # Boeken - Reisgidsen
    - 4294754280
    - 6080 # Muziek POP
    - 6142 # Film + tv Actie en Avontuur
    - 6158
    - 6196 # Film + tv Humor
    - 10579
    - 10596
    - 12432 # Mooi en gezond Herengeuren
    - 11897 # koken en tafelen - Wijn en bar - Thuistappen
    - 11772 # koken en tafelen - Barbecues
    - 11773
    - 11785
    - 11897 # koken en tafelen - Wijn en bar - Wijnrekken
    - 11962 # elektronica -keukenapparaten-bak-grillplaten - grillplaten
    - 11826
    - 8429
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10824
    - 10836
    - 10771
    - 10798
    - 10799
    - 10802
    - 10800
    - 10728
    - 10727
    - 10730
    - 10732

- id: 'moeder'
  name: Voor je moeder
  categories:
    - 1430 # Categorie - Nederlandse boeken
    - 19
    - 3131 # Categorie - Engelse Boeken
    - 263 # Boeken - Wonen en Tuinieren
    - 105 # Boeken - Reisgidsen
    - 32 # Boeken - Bekende koks
    - 31 # Boeken - Kookboeken
    - 6080 # Muziek POP
    - 6177 # Film + tv Filmhuis en internationaal
    - 6196 # Film + tv Humor
    - 6230 # Film + tv drama en romantiek
    - 6251 # Film + tv Thrillers & Crime
    - 10508 # handwerken en mode
    - 10511 # Koken en bakken
    - 10506 # Boetseren en vormgeven
    - 10564 # legpuzzels
    - 12383
    - 12429 # Mooi en gezond Damesgeuren
    - 12687 # Mooi en gezond Persoonlijke verzorging geschenksets
    - 12441 # Mooi en gezond Geurengeschenksets
    - 11900 # koken en tafelen - Wijn en bar - Decanteerkarraffen
    - 11907 # koken en tafelen - Wijn en bar - Wijnglazen
    - 11897 # koken en tafelen - Wijn en bar - Wijnkoelers
    - 11897 # koken en tafelen - Wijn en bar - Wijnrekken
    - 11903 # koken en tafelen - Wijn en bar - Openers
    - 11926 # koken en tafelen - Tafellakens
    - 11962 # elektronica -keukenapparaten-bak-grillplaten - grillplaten
    - 11773
    - 11785
    - 11826
    - 11922
    - 11927
    - 11888
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10829
    - 10832
    - 10771
    - 10798
    - 10799
    - 10802
    - 10800
    - 14768 # Sport - Pilates en Yoga

- id: 'broertje'
  name: Voor je broertje
  categories:
    - 1430 # Categorie - Nederlandse boeken
    - 19
    - 3131 # Categorie - Engelse Boeken
    - 105 # Boeken - Reisgidsen
    - 4294754280
    - 3132 # muziek totaal
    - 6142 # Film + tv Actie en Avontuur
    - 6196 # Film + tv Humor
    - 11551 # Games XBOX One
    - 11642 # Games Playstaytion 4
    - 5201 # Games PC
    - 10500 # Speelgoed Electronisch speelgoed
    - 10579
    - 10596
    - 12432 # Mooi en gezond Herengeuren
    - 11897 # koken en tafelen - Wijn en bar - Thuistappen
    - 4098
    - 8427
    - 8431
    - 8429
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10824
    - 10836
    - 10728
    - 10727
    - 10730
    - 10732

- id: 'zusje'
  name: Voor je zusje
  categories:
    - 1430 # Categorie - Nederlandse boeken
    - 19
    - 3131 # Categorie - Engelse Boeken
    - 105 # Boeken - Reisgidsen
    - 4284431352
    - 3132 # muziek totaal
    - 6080 # Muziek POP
    - 6196 # Film + tv Humor
    - 6230 # Film + tv drama en romantiek
    - 10508 # handwerken en mode
    - 10511 # Koken en bakken
    - 10506 # Boetseren en vormgeven
    - 12383
    - 12429 # Mooi en gezond Damesgeuren
    - 12687 # Mooi en gezond Persoonlijke verzorging geschenksets
    - 12441 # Mooi en gezond Geurengeschenksets
    - 11907 # koken en tafelen - Wijn en bar - Wijnglazen
    - 11897 # koken en tafelen - Wijn en bar - Wijnrekken
    - 4098
    - 8427
    - 8431
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10829
    - 10832
    - 14768 # Sport - Pilates en Yoga

- id: 'baby'
  name: Voor een baby
  categories:
    - 10528
    - 10535
    - 10477
    - 11299 # Baby Babykamer hemeltjes
    - 11285 # Baby Speelgoed voor onderweg
    - 7195

- id: 'oma'
  name: Voor je oma
  categories:
    - 1430 # Categorie - Nederlandse boeken
    - 32 # Boeken - Bekende koks
    - 31 # Boeken - Kookboeken
    - 263 # Boeken - Wonen en Tuinieren
    - 19
    - 6046
    - 10508 # handwerken en mode
    - 10511 # Koken en bakken
    - 10506 # Boetseren en vormgeven
    - 10564 # legpuzzels
    - 12383
    - 12429 # Mooi en gezond Damesgeuren
    - 12687 # Mooi en gezond Persoonlijke verzorging geschenksets
    - 12441 # Mooi en gezond Geurengeschenksets
    - 11773
    - 11926 # koken en tafelen - Tafellakens
    - 11785
    - 11826
    - 11922
    - 11927
    - 11888
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10829
    - 10832
    - 10771
    - 10798
    - 10799
    - 10802
    - 10800

- id: 'opa'
  name: Voor je opa
  categories:
    - 1430 # Categorie - Nederlandse boeken
    - 105 # Boeken - Reisgidsen
    - 19
    - 4294754280
    - 6046
    - 10564 # legpuzzels
    - 12432 # Mooi en gezond Herengeuren
    - 11897 # koken en tafelen - Wijn en bar - Thuistappen
    - 11772 # koken en tafelen - Barbecues
    - 11773
    - 11785
    - 11826
    - 4070 # Digitale fotografie - digitale camera's
    - 10661
    - 10824
    - 10836
    - 10771
    - 10798
    - 10799
    - 10802
    - 10800
    - 11962 # elektronica -keukenapparaten-bak-grillplaten - grillplaten

- id: 'huwelijk'
  name: Huwelijkscadeau
  categories:
    - 1430 # Categorie - Nederlandse boeken
    - 4070 # Digitale fotografie - digitale camera's
    - 11809 # Kookgerei - Peper en zoutstellen
    - 11867 # koken en tafelen - kookgerei - Servies
    - 11877 # koken en tafelen - kookgerei - Bestek
    - 11768 # koken en tafelen - kookgerei - Pannensets
    - 11897 # koken en tafelen - Wijn en bar - Thuistappen
    - 11900 # koken en tafelen - Wijn en bar - Decanteerkarraffen
    - 11907 # koken en tafelen - Wijn en bar - Wijnglazen
    - 11897 # koken en tafelen - Wijn en bar - Wijnkoelers
    - 11897 # koken en tafelen - Wijn en bar - Wijnrekken
    - 11903 # koken en tafelen - Wijn en bar - Openers
    - 11926 # koken en tafelen - Tafellakens
    - 11945 # koken en tafelen - esspressomachine
    - 11961 # koken en tafelen - gourmetteset
    - 11772 # koken en tafelen - Barbecues
    - 11962 # elektronica -keukenapparaten-bak-grillplaten - grillplaten
    - 32 # Boeken - Bekende koks
    - 31 # Boeken - Kookboeken
    - 263 # Boeken - Wonen en Tuinieren
    - 105 # Boeken - Reisgidsen

    

# - id: 'huwelijk'
#   name: Een bruidspaar
#   categories:
#     - bla
